### ISSUE TITLE
Are any audio functions at all supported?

### ISSUE THREAD

**Issue by AdityaAnand1** [inFullMobile/videokit-ffmpeg-android#10]
I was wondering if this library works exclusively for video processing only or also for audio?

**Comment by IljaKosynkin** [comment]
Hello, @AdityaAnand1 
I didn't try anything related to audio explicitly (beside removing audio tracks from video file), but since it's wrapper around FFmpeg library, I don't see why it wouldn't work. 
Current version of FFmpeg used is 3.0.2, so, theoretically, you should be able to run any command that you can run with usual FFMpeg thru VideoKit's custom command interface.
If you have any issues with that: fell free to post it here.

**Comment by IljaKosynkin** [comment]
I'm assuming that issue was resolved and closing it @AdityaAnand1. If there are still issues related to audio functions of FFmpeg - feel free to open new one.
