### ISSUE TITLE
I am getting no implementation found error.

### ISSUE THREAD

**Issue by sluitel** [inFullMobile/videokit-ffmpeg-android#12]
I am using this for implementing watermark over a video. It works great on Samsung Galaxy S5. However on the later devices it crashes with the following error:

> No implementation found for int processing.ffmpeg.videokit.VideoKit.run(int, java.lang.String[]) (tried Java_processing_ffmpeg_videokit_VideoKit_run and Java_processing_ffmpeg_videokit_VideoKit_run__I_3Ljava_lang_String_2)

I am using to following code to do a watermark over a video:

```
final Command command = videoKit.createCommand()
                .overwriteOutput()
                .inputPath(videoPath)
                .customCommand("-i " + stickerPath)
                .outputPath(newVideoPath)
                .customCommand("-filter_complex overlay=1:1")
                .experimentalFlag()
                .build();
        command.execute();
```

**Comment by IljaKosynkin** [comment]
@sluitel hello.
Can you provide model of crashing phone? Such crash means that there are no .so files for architecture of this particular phone and I was pretty sure that I've covered most popular ones.

**Comment by sluitel** [comment]
Hi @IljaKosynkin, thanks for the reply. It looks like its happening on every phone with api version higher than 23. I tried changing the sdkTargetVersion to 22 and it works great, but it gives the error on sdkTargetVersion 23 and higher. The problem is I already have an app on the play sdkTargetVersion 25 and I am not able to downgrade to target 23.

**Comment by sluitel** [comment]
I am also getting this warning. This must be related to this issue

> java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/......../lib/x86/libswresample-1.so: has text relocations

**Comment by IljaKosynkin** [comment]
@sluitel hmm, ok, I see. It seems that API > 22 is no longer allows native libraries with "text relocations" to be loaded (swresample, part of FFmpeg in our case, cannot be loaded). It's quite strange because I had strong belief that I've tested sample on 23+ version. Probably it was before introducing FFmpeg 3.2 and NDK r13 (sample used target API version equal to 22, not 25 as now).
Anyway, it's not really related to VideoKit, rather to FFmpeg itself. I cannot make any promises when I will be able to look more precisely into this issue, because I would need to dive into FFmpeg code, most probably (quite likely that it will require changes in .asm code).
If you need it ASAP, I would suggest you to compile your own version of VideoKit with --disable-asm flag as suggested here: [avcodec has text relocations](http://stackoverflow.com/a/35793766). . **It will affect performance quite hard.** If you decide to go that way, I would suggest to use [FFmpeg Development Kit](https://github.com/IljaKosynkin/FFmpeg-Development-Kit) for that. Modify file "build_all.sh" in folder ffmpeg in following way:
`export COMMON="--disable-static --disable-programs --disable-doc --enable-shared --enable-protocol=file --disable-asm"`
and follow instructions in readme to build .so files. I would suggest to build one architecture at time to catch out possible errors related to concrete architecture. Right now build_all.sh builds only x86_64, just uncomment architectures one by one (commenting all other) and rerun script.
Note, that I used NDK r13b and FFmpeg 3.2.4. You can grab newer versions, but it might won't work together. If you want to test your fortune and try out newer versions - make sure to copy files "build_*.sh", ModuleParser.py, FFmpegParser.py and Android.mk to new directory of FFmpeg and make sure that this directory is named "ffmpeg" and then replace directory  "ffmpeg" in repo with your new one.
Another option might be to use MediaCodec instead, which will be way faster and effective, but most likely will work only for videos that were recorded on this particular device.
Make sure to read this [question](http://stackoverflow.com/questions/36808806/android-fast-video-processing) and especially "update" section if you decide to go that way.

**Comment by sluitel** [comment]
Hi @IljaKosynkin, Thank you so much for the detail explanation. It all makes sense. I am quite new to android development and Videokit was simple enough for me to use and test. I tried to compile the NDK using FFMpeg Development Kit but can't get it to work. I followed the instructions and all. I tried everything I could and at the end I'm running out of options. Is there any way you could create a branch on VideoKit for ffmpeg compiled using --disabled-asm so I could use that?

**Comment by IljaKosynkin** [comment]
Hello @sluitel. I think I actually, managed to resolve issue. I will make PR tomorrow and it's quite possible that I will push next fixed version tomorrow to Maven (although, it will be without mips - recent versions of FFmpeg seems to have problem with this architecture). I will let you know once new version will be ready.

**Comment by sluitel** [comment]
Awesome!!! Thanks so much.

**Comment by IljaKosynkin** [comment]
@sluitel please try version 1.1.1 and let me know if it works or no.

**Comment by sluitel** [comment]
Hi @IljaKosynkin. I am still getting the same error.

```
FATAL EXCEPTION: main
Process: tv.upshow.headsup, PID: 31023
java.lang.UnsatisfiedLinkError: No implementation found for int processing.ffmpeg.videokit.VideoKit.run(int, java.lang.String[]) (tried Java_processing_ffmpeg_videokit_VideoKit_run and Java_processing_ffmpeg_videokit_VideoKit_run__I_3Ljava_lang_String_2)
at processing.ffmpeg.videokit.VideoKit.run(Native Method)
at processing.ffmpeg.videokit.VideoKit.process(VideoKit.java:30)
at processing.ffmpeg.videokit.VideoCommand.execute(VideoCommand.java:26)
at tv.upshow.headsup.CapturedImageActivity.attachStickersToVideo(CapturedImageActivity.java:303)
```

**Comment by IljaKosynkin** [comment]
@sluitel are there any warnings before this exception? Can you provide on which device do you getting this exception?

**Comment by sluitel** [comment]
@IljaKosynkin yes.
```
E/linker: /data/app/*****-1/lib/x86/libswresample.so: has text relocations
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/******-1/lib/x86/libswresample.so: has text relocations
at java.lang.Runtime.loadLibrary0(Runtime.java:977)
at java.lang.System.loadLibrary(System.java:1530)
at processing.ffmpeg.videokit.VideoKit.<clinit>(VideoKit.java:11)
```

**Comment by sluitel** [comment]
I ran on Google pixel and google nexus five

**Comment by IljaKosynkin** [comment]
@sluitel hmm, I will try to test it on Nexus 5 tomorrow in office. In meantime, can you download current master and try to run sample on one of those devices?

**Comment by sluitel** [comment]
@IljaKosynkin I actually tried downloading the master as well. Same error. btw I was testing on emulators not on actual devices.

**Comment by sluitel** [comment]
I tested on an actual device (Samsung Galaxy S7 API 24). It worked!!!!

**Comment by IljaKosynkin** [comment]
@sluitel ye, I'm a bit surprised it is not working on emulators. I will test it by myself.

**Comment by IljaKosynkin** [comment]
@sluitel try v1.1.2 please. It should work both on simulators and on real devices.

**Comment by sluitel** [comment]
@IljaKosynkin Awesome!! Thanks.

**Comment by IljaKosynkin** [comment]
@sluitel so issue got resolved? Can I close it now?

**Comment by sluitel** [comment]
@IljaKosynkin Work like a charm. Really appreciate your help.
