### ISSUE TITLE
Can not use crop command

### ISSUE THREAD

**Issue by kazixma** [inFullMobile/videokit-ffmpeg-android#8]
final Command command = videoKit.createCommand()
                .inputPath(path)
                .outputPath(System.currentTimeMillis() + POSTFIX)
                .crop(0,0,300,300)
                .experimentalFlag()
                .build();

It can not use crop command 

Log show 

> 03-20 02:23:40.610 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: ffmpeg
03-20 02:23:40.610 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: -i
03-20 02:23:40.610 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: /storage/emulated/0/intro.mp4
03-20 02:23:40.611 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: -vf
03-20 02:23:40.611 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: crop=300:300:0:0
03-20 02:23:40.611 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: -strict
03-20 02:23:40.611 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: -2
03-20 02:23:40.611 27785-28025/ffmpeg.videokit.sample I/Videokit: Option: 1489951420608.mp4

And I want to use custom command and it show error same crop command 

this command I want to use 

> -vf crop=iw:iw,scale=480:ih*480/iw -threads 5 -preset ultrafast -strict -2

**Comment by IljaKosynkin** [comment]
@kazixma Good afternoon.
Hm, it seems that I missed this moment in documentation (I was 100% sure that I did described it): basically, 
```java
CommandBuilder customCommand(String customCommand);
```
is adding customCommand as separate option, so if you have something like this:
```java
  final Command command = videoKit.createCommand()
            .inputPath(path)
            .outputPath(System.currentTimeMillis() + POSTFIX)
            .crop(0,0,300,300)
            . customCommand("-vf crop=iw:iw,scale=480:ih*480/iw -threads 5 -preset ultrafast")
            .experimentalFlag()
            .build();
```
will result in error because constructed CLI command will look like:
```bash
ffmpeg -i <path> -vf crop=300:300:0:0 -vf crop=iw:iw,scale=480:ih*480/iw -threads 5 -preset ultrafast -strict -2 <output>
```
To avoid this, you might use something like this:
```java
  final Command command = videoKit.createCommand()
            .inputPath(path)
            .outputPath(System.currentTimeMillis() + POSTFIX)
            . customCommand("-vf crop=iw:iw,scale=480:ih*480/iw -threads 5 -preset ultrafast")
            .experimentalFlag()
            .build();
```
Also, as sidenote - I believe **"-preset ultrafast" is part of libx264 which is not linked with VideoKit, since it's licensed under GPL, not LGPL**. If you really need to use libx264 and license is not problem for you, I would suggest you to build FFmpeg with libx264 by yourself. 
You can use [FFmpeg Development Kit](https://github.com/IljaKosynkin/FFmpeg-Development-Kit), it's developed by me and should make process of building significantly easier. 
Also, I wrote post that should help with manual process of FFmpeg building [Building FFmpeg for Android](https://syllogismobile.wordpress.com/2017/02/19/building-ffmpeg-for-android/), you might want check it as well.

**Comment by IljaKosynkin** [comment]
No response from the author for more then week. Closing issue as resolved.
@kazixma if your issue still not solved -open another one please.
